//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCRI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosage
    {
        public Dosage()
        {
            this.Drugs = new HashSet<Drug>();
        }
    
        public string dosage_Code { get; set; }
        public string dosage_Description { get; set; }
        public string created_By { get; set; }
        public System.DateTime date_created { get; set; }
    
        public virtual ULogin ULogin { get; set; }
        public virtual ICollection<Drug> Drugs { get; set; }
    }
}
