//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCRI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public Drug()
        {
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public string drug_Code { get; set; }
        public string drug_Name { get; set; }
        public string trade_Code { get; set; }
        public string dosage_Code { get; set; }
        public string formulation_Code { get; set; }
        public System.DateTime date_Created { get; set; }
        public string Created_By { get; set; }
    
        public virtual Dosage Dosage { get; set; }
        public virtual Formulation Formulation { get; set; }
        public virtual Trade Trade { get; set; }
        public virtual ULogin ULogin { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
