//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCRI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formulation
    {
        public Formulation()
        {
            this.Drugs = new HashSet<Drug>();
        }
    
        public string formulation_code { get; set; }
        public string formulation_Name { get; set; }
        public string description { get; set; }
        public string shortName { get; set; }
        public string created_By { get; set; }
        public System.DateTime date_Created { get; set; }
    
        public virtual ICollection<Drug> Drugs { get; set; }
        public virtual ULogin ULogin { get; set; }
    }
}
