//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCRI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public PurchaseOrder()
        {
            this.Stocks = new HashSet<Stock>();
        }
    
        public string po_Code { get; set; }
        public System.DateTime po_Date { get; set; }
        public string drug_Code { get; set; }
        public string supplier_Code { get; set; }
        public int po_Quantity { get; set; }
        public string Ordered_By { get; set; }
        public System.DateTime date_Created { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ULogin ULogin { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
