//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCRI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public string stock_Code { get; set; }
        public System.DateTime stock_ReceivedDate { get; set; }
        public int stock_ReceivedQuantity { get; set; }
        public string po_Code { get; set; }
        public string batchCode { get; set; }
        public System.DateTime expiry_Date { get; set; }
        public bool IsActive { get; set; }
        public int stock_BalanceQuantity { get; set; }
        public string created_By { get; set; }
        public System.DateTime date_Created { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual ULogin ULogin { get; set; }
    }
}
