//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCRI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string transaction_Code { get; set; }
        public string drug_Code { get; set; }
        public int drug_Quantity { get; set; }
        public string sold_By { get; set; }
        public System.DateTime sold_Date { get; set; }
        public string Comment { get; set; }
        public string BuyerName { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual ULogin ULogin { get; set; }
    }
}
