//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCRI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ULogin
    {
        public ULogin()
        {
            this.Dosages = new HashSet<Dosage>();
            this.Drugs = new HashSet<Drug>();
            this.Formulations = new HashSet<Formulation>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.Stocks = new HashSet<Stock>();
            this.Suppliers = new HashSet<Supplier>();
            this.Trades = new HashSet<Trade>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public string user_ID { get; set; }
        public string user_Name { get; set; }
        public string user_Pwd { get; set; }
        public string role { get; set; }
        public System.DateTime date_Created { get; set; }
        public int SNo { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Dosage> Dosages { get; set; }
        public virtual ICollection<Drug> Drugs { get; set; }
        public virtual ICollection<Formulation> Formulations { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual ICollection<Trade> Trades { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
