//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCR_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public Drug()
        {
            this.Orders = new HashSet<Order>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public string Drug_Code { get; set; }
        public string Drug_Name { get; set; }
        public string Trade_Code { get; set; }
        public string Dosage_Code { get; set; }
        public string Formulation_code { get; set; }
        public Nullable<System.DateTime> Created_Datetime { get; set; }
        public string Created_By { get; set; }
    
        public virtual Dosage Dosage { get; set; }
        public virtual Formulation Formulation { get; set; }
        public virtual Login Login { get; set; }
        public virtual Trade Trade { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
