//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCR_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public string Drug_Code { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Expiry_Date { get; set; }
        public bool IsActive { get; set; }
        public int Stock_ID { get; set; }
    
        public virtual Drug Drug { get; set; }
    }
}
